### ISSUE TITLE
The bitcache.org page appears hacked

### ISSUE THREAD

**Issue by wscott** [dryruby/bitcache#1]
The license on the homepage at bitcache.org points at some Las Vagas carpet cleaning website.
I suspect your page was hacked.

**Comment by artob** [comment]
Unfortunately, I no longer control the domain. Whoever grabbed it (the whois information is private) seems to have explicitly gone to the trouble of mirroring some aspects of the old genuine site, and then inserting spam links. There's no recourse that I can conceive of.

Thanks for the report in any case.

**Comment by wscott** [comment]
Well... bitcache.org is linked from http://sourceforge.net/projects/bitcache/

**Comment by artob** [comment]
Thanks for the tip. I've now removed the link from SF.
